const $=s=>document.querySelector(s);
let catalog={movies:[],meta:{}}, movies=[];
const state={query:'',genre:'',year:'',watchlist:new Set(JSON.parse(localStorage.getItem('nm-watchlist')||'[]')),history:JSON.parse(localStorage.getItem('nm-history')||'[]')};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();
function saveState(){localStorage.setItem('nm-watchlist',JSON.stringify([...state.watchlist]));localStorage.setItem('nm-history',JSON.stringify(state.history));}
function card(m){return `<article class="card" data-id="${esc(m.id)}"><div class="poster"><img loading="lazy" src="${esc(m.thumbnail||'assets/poster-placeholder.svg')}" alt="${esc(m.title)}" onerror="this.onerror=null;this.src='assets/poster-placeholder.svg'"><span class="quality">${m.duration||formatDuration(m.durationSeconds)}</span></div><div class="card-title">${esc(m.title)}</div><p class="card-meta">${esc(m.year||'')} · ${esc((m.genre||['Cinema'])[0])}</p></article>`}
function formatDuration(s){s=Number(s||0);if(!s)return '';let h=Math.floor(s/3600),m=Math.floor(s%3600/60);return h?`${h}h ${m}m`:`${m}m`}
function bindCards(){document.querySelectorAll('.card').forEach(x=>x.onclick=()=>openMovie(movies.find(m=>m.id===x.dataset.id)));}
function score(m){return Number(m.algorithm?.recommendationScore??m.algorithm?.trendingScore??0)}
function similarity(a,b){let s=0;const ag=new Set(a.genre||[]),bg=new Set(b.genre||[]);const overlap=[...ag].filter(x=>bg.has(x)).length;s+=overlap*35;if(a.year&&b.year)s+=Math.max(0,12-Math.abs(a.year-b.year)*2);if(a.creator?.channelId&&a.creator.channelId===b.creator?.channelId)s+=25;return s}
function similar(m){return movies.filter(x=>x.id!==m.id).map(x=>[similarity(m,x)+Math.min(20,score(x)/5),x]).sort((a,b)=>b[0]-a[0]).slice(0,12).map(x=>x[1]);}
function personalized(){if(!state.history.length)return [];const watched=state.history.map(id=>movies.find(m=>m.id===id)).filter(Boolean);const genreWeight={},creatorWeight={};watched.forEach((m,i)=>{const w=Math.max(1,8-i);(m.genre||[]).forEach(g=>genreWeight[g]=(genreWeight[g]||0)+w);if(m.creator?.channelId)creatorWeight[m.creator.channelId]=(creatorWeight[m.creator.channelId]||0)+w;});return movies.filter(m=>!state.history.includes(m.id)).map(m=>{let s=score(m)*.25;(m.genre||[]).forEach(g=>s+=(genreWeight[g]||0)*7);if(m.creator?.channelId)s+=(creatorWeight[m.creator.channelId]||0)*10;return [s,m]}).sort((a,b)=>b[0]-a[0]).slice(0,12).map(x=>x[1]);}
function related(m){return similar(m)}
function openMovie(m){if(!m)return;state.history=[m.id,...state.history.filter(id=>id!==m.id)].slice(0,50);saveState();$('#playerTitle').textContent=m.title;$('#playerCreator').textContent=m.creator?.name?`Source: ${m.creator.name}`:'Source: YouTube';$('#playerMeta').textContent=`${m.year||''} · ${(m.genre||[]).join(' · ')} · ${formatDuration(m.durationSeconds)}`;$('#playerDesc').textContent=m.description||'Discover this Nepali movie from its original YouTube source.';$('#saveBtn').textContent=state.watchlist.has(m.id)?'♥ Saved':'♡ Save';$('#saveBtn').onclick=()=>{state.watchlist.has(m.id)?state.watchlist.delete(m.id):state.watchlist.add(m.id);saveState();$('#saveBtn').textContent=state.watchlist.has(m.id)?'♥ Saved':'♡ Save';};$('#player').src=`https://www.youtube.com/embed/${encodeURIComponent(m.youtubeVideoId)}?autoplay=1&rel=0&playsinline=1`;$('#relatedRail').innerHTML=related(m).map(card).join('');bindCards();$('#playerModal').classList.remove('hidden');document.body.classList.add('locked');}
function closePlayer(){$('#player').src='';$('#playerModal').classList.add('hidden');document.body.classList.remove('locked');renderPersonalized();}
function renderPersonalized(){const fy=personalized();const watched=state.history.map(id=>movies.find(m=>m.id===id)).filter(Boolean).slice(0,12);$('#forYouSection').classList.toggle('hidden',!fy.length);$('#continueSection').classList.toggle('hidden',!watched.length);$('#forYouRail').innerHTML=fy.map(card).join('');$('#continueRail').innerHTML=watched.map(card).join('');bindCards();}
function render(){let pool=movies.filter(m=>!state.genre||((m.genre||[]).includes(state.genre)));if(state.year)pool=pool.filter(m=>String(m.year)===state.year);let q=norm(state.query);if(q){const terms=q.split(' ').filter(Boolean);pool=pool.map(m=>{const hay=norm(`${m.title} ${m.creator?.name||''} ${(m.genre||[]).join(' ')} ${m.year||''}`);let relevance=terms.reduce((n,t)=>n+(hay.includes(t)?1:0),0);return [relevance,m]}).filter(x=>x[0]>0).sort((a,b)=>b[0]-a[0]||score(b[1])-score(a[1])).map(x=>x[1]);}let trending=[...movies].sort((a,b)=>score(b)-score(a)).slice(0,12);let latest=[...movies].sort((a,b)=>new Date(b.publishedDate||0)-new Date(a.publishedDate||0)).slice(0,12);$('#trendingRail').innerHTML=trending.map(card).join('');$('#latestRail').innerHTML=latest.map(card).join('');$('#movieGrid').innerHTML=pool.map(card).join('')||'<div class="empty"><h3>No movies found</h3><p>Try another title, year or genre.</p></div>';let genres=[...new Set(movies.flatMap(m=>m.genre||[]))].sort();$('#genres').innerHTML=genres.map(g=>`<button class="genre ${state.genre===g?'selected':''}" data-g="${esc(g)}">${esc(g)}</button>`).join('');$('#yearFilter').innerHTML='<option value="">All years</option>'+[...new Set(movies.map(m=>m.year).filter(Boolean))].sort((a,b)=>b-a).map(y=>`<option value="${y}" ${String(state.year)===String(y)?'selected':''}>${y}</option>`).join('');bindCards();document.querySelectorAll('.genre').forEach(b=>b.onclick=()=>{state.genre=b.dataset.g===state.genre?'':b.dataset.g;render();});renderPersonalized();}
function renderLibrary(){let list=movies.filter(m=>state.watchlist.has(m.id));$('#watchlistGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">Your saved movies will appear here.</div>';bindCards();}
function renderHistory(){let list=state.history.map(id=>movies.find(m=>m.id===id)).filter(Boolean);$('#historyGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">No watch history yet.</div>';bindCards();}
function showPage(name){document.querySelectorAll('.page,.content').forEach(x=>x.classList.add('hidden'));let el=name==='home'?$('#home'):name==='library'?$('#libraryPage'):name==='profile'?$('#profilePage'):$('#home');el.classList.remove('hidden');document.querySelectorAll('.bottom-nav [data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===name));if(name==='library')renderLibrary();if(name==='profile')renderHistory();window.scrollTo({top:0,behavior:'smooth'});}
function searchOpen(){ $('#searchPanel').classList.remove('hidden');$('#searchInput').focus();window.scrollTo({top:0,behavior:'smooth'});}
async function init(){try{let r=await fetch('data/movies.json',{cache:'no-cache'});if(!r.ok)throw Error('catalog');catalog=await r.json();movies=catalog.movies||[];render();}catch(e){$('#movieGrid').innerHTML='<div class="empty"><h3>Catalog unavailable</h3><p>Please try again later.</p><button class="primary" onclick="location.reload()">Retry</button></div>';}}
$('#closeModal').onclick=closePlayer;$('#searchBtn').onclick=searchOpen;$('#navSearch').onclick=searchOpen;$('#clearSearch').onclick=()=>{$('#searchInput').value='';state.query='';render();};$('#searchInput').oninput=e=>{state.query=e.target.value;render();};$('#yearFilter').onchange=e=>{state.year=e.target.value;render();};$('#heroPlay').onclick=()=>document.querySelector('#trendingRail').scrollIntoView({behavior:'smooth'});$('#clearHistory').onclick=()=>{state.history=[];saveState();renderHistory();renderPersonalized();};document.querySelectorAll('.bottom-nav [data-page]').forEach(x=>x.onclick=e=>{e.preventDefault();showPage(x.dataset.page);});window.addEventListener('keydown',e=>{if(e.key==='Escape')closePlayer();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchOpen();}});init();