const $=s=>document.querySelector(s);
let catalog={movies:[],meta:{}}, movies=[];
const state={query:'',genre:'',year:'',watchlist:new Set(JSON.parse(localStorage.getItem('nm-watchlist')||'[]')),history:JSON.parse(localStorage.getItem('nm-history')||'[]')};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function saveState(){localStorage.setItem('nm-watchlist',JSON.stringify([...state.watchlist]));localStorage.setItem('nm-history',JSON.stringify(state.history));}
function card(m){return `<article class="card" data-id="${esc(m.id)}"><div class="poster"><img loading="lazy" src="${esc(m.thumbnail||'assets/poster-placeholder.svg')}" alt="${esc(m.title)}" onerror="this.onerror=null;this.src='assets/poster-placeholder.svg'"><span class="quality">${m.duration||''}</span></div><div class="card-title">${esc(m.title)}</div><p class="card-meta">${esc(m.year||'')} · ${esc((m.genre||['Cinema'])[0])}</p></article>`}
function bindCards(){document.querySelectorAll('.card').forEach(x=>x.onclick=()=>openMovie(movies.find(m=>m.id===x.dataset.id)));}
function score(m){return Number(m.algorithm?.recommendationScore??m.algorithm?.trendingScore??0)}
function similar(m){return movies.filter(x=>x.id!==m.id).map(x=>{let s=0;if((m.genre||[]).some(g=>(x.genre||[]).includes(g)))s+=40;if(m.year&&x.year&&Math.abs(m.year-x.year)<=5)s+=10;if(m.creator?.channelId&&m.creator.channelId===x.creator?.channelId)s+=25;s+=Math.min(25,score(x)/4);return [s,x]}).sort((a,b)=>b[0]-a[0]).slice(0,10).map(x=>x[1]);}
function related(m){return similar(m)}
function openMovie(m){if(!m)return;state.history=[m.id,...state.history.filter(id=>id!==m.id)].slice(0,50);saveState();$('#playerTitle').textContent=m.title;$('#playerCreator').textContent=m.creator?.name?`Source: ${m.creator.name}`:'Source: YouTube';$('#playerMeta').textContent=`${m.year||''} · ${(m.genre||[]).join(' · ')}`;$('#playerDesc').textContent=m.description||'Discover this Nepali movie from its original YouTube source.';$('#saveBtn').textContent=state.watchlist.has(m.id)?'♥ Saved':'♡ Save';$('#saveBtn').onclick=()=>{state.watchlist.has(m.id)?state.watchlist.delete(m.id):state.watchlist.add(m.id);saveState();$('#saveBtn').textContent=state.watchlist.has(m.id)?'♥ Saved':'♡ Save';};$('#player').src=`https://www.youtube.com/embed/${encodeURIComponent(m.youtubeVideoId)}?autoplay=1&rel=0&playsinline=1`;$('#relatedRail').innerHTML=related(m).map(card).join('');bindCards();$('#playerModal').classList.remove('hidden');document.body.classList.add('locked');}
function closePlayer(){$('#player').src='';$('#playerModal').classList.add('hidden');document.body.classList.remove('locked');}
function render(){let pool=movies.filter(m=>!state.genre||((m.genre||[]).includes(state.genre)));if(state.year)pool=pool.filter(m=>String(m.year)===state.year);let q=state.query.trim().toLowerCase();if(q)pool=pool.filter(m=>(`${m.title} ${m.creator?.name||''} ${(m.genre||[]).join(' ')} ${m.year||''}`).toLowerCase().includes(q));let trending=[...movies].sort((a,b)=>score(b)-score(a)).slice(0,12);let latest=[...movies].sort((a,b)=>new Date(b.publishedDate||0)-new Date(a.publishedDate||0)).slice(0,12);$('#trendingRail').innerHTML=trending.map(card).join('');$('#latestRail').innerHTML=latest.map(card).join('');$('#movieGrid').innerHTML=pool.map(card).join('');let genres=[...new Set(movies.flatMap(m=>m.genre||[]))].sort();$('#genres').innerHTML=genres.map(g=>`<button class="genre ${state.genre===g?'selected':''}" data-g="${esc(g)}">${esc(g)}</button>`).join('');$('#yearFilter').innerHTML='<option value="">All years</option>'+[...new Set(movies.map(m=>m.year).filter(Boolean))].sort((a,b)=>b-a).map(y=>`<option value="${y}" ${String(state.year)===String(y)?'selected':''}>${y}</option>`).join('');bindCards();document.querySelectorAll('.genre').forEach(b=>b.onclick=()=>{state.genre=b.dataset.g===state.genre?'':b.dataset.g;render();});}
function renderLibrary(){let list=movies.filter(m=>state.watchlist.has(m.id));$('#watchlistGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">Your saved movies will appear here.</div>';bindCards();}
function renderHistory(){let list=state.history.map(id=>movies.find(m=>m.id===id)).filter(Boolean);$('#historyGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">No watch history yet.</div>';bindCards();}
function showPage(name){document.querySelectorAll('.page,.content').forEach(x=>x.classList.add('hidden'));let el=name==='home'?$('#home'):name==='library'?$('#libraryPage'):name==='profile'?$('#profilePage'):$('#home');el.classList.remove('hidden');document.querySelectorAll('.bottom-nav [data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===name));if(name==='library')renderLibrary();if(name==='profile')renderHistory();window.scrollTo({top:0,behavior:'smooth'});}
function searchOpen(){ $('#searchPanel').classList.remove('hidden');$('#searchInput').focus();window.scrollTo({top:0,behavior:'smooth'});}
async function init(){try{let r=await fetch('data/movies.json',{cache:'no-cache'});if(!r.ok)throw Error('catalog');catalog=await r.json();movies=catalog.movies||[];render();}catch(e){$('#movieGrid').innerHTML='<div class="empty"><h3>Catalog unavailable</h3><p>Please try again later.</p><button class="primary" onclick="location.reload()">Retry</button></div>';}}
$('#closeModal').onclick=closePlayer;$('#searchBtn').onclick=searchOpen;$('#navSearch').onclick=searchOpen;$('#clearSearch').onclick=()=>{$('#searchInput').value='';state.query='';render();};$('#searchInput').oninput=e=>{state.query=e.target.value;render();};$('#yearFilter').onchange=e=>{state.year=e.target.value;render();};$('#heroPlay').onclick=()=>document.querySelector('#trendingRail').scrollIntoView({behavior:'smooth'});$('#clearHistory').onclick=()=>{state.history=[];saveState();renderHistory();};document.querySelectorAll('.bottom-nav [data-page]').forEach(x=>x.onclick=e=>{e.preventDefault();showPage(x.dataset.page);});window.addEventListener('keydown',e=>{if(e.key==='Escape')closePlayer();});
init();